### PR TITLE
Fix footer and time #145

### LINKED ISSUE #144: Web: Should have a facebook badge linking to our facebook page.

### LINKED ISSUE #145: Web: Change phrasing in footer and explicitly state that transfers has to be done before 14:00

### PR DESCRIPTION
**Pull request by hafager**
Fixes #145, fixes #144

### CODE REVIEW

File: web/src/views/app/footer/Footer.js [hunk 1]
```diff
@@ -1,11 +1,12 @@
 import React from 'react';
+import { IoSocialFacebook } from 'react-icons/lib/io';
 
 import { Grid, Column } from '../../../components/grid';
 
-const footerIntro = 'Dette prosjektet er et ikke-kommersielt skoleprosjekt, og er først fremst laget av utdanningsmessige grunner.';
-const copyrightInfo = 'Dersom du eier noe av innholdet ønsker at vi skal fjerne det, vennligst ta kontakt.';
+const footerIntro = 'Dette prosjektet er et ikke-kommersielt studentprosjekt, og er først og fremst laget av utdanningsmessige hensikter.';
```
Comment (Khrall) [inline web/src/views/app/footer/Footer.js]: "..laget _med_ utdanningsmessige hensikter"?

Comment (hafager) [inline web/src/views/app/footer/Footer.js]: Fixed

**Comment by hafager** [comment]
Did some more changes to the transfer box.
