### PR TITLE
Cache stats#105

### LINKED ISSUE #105: API: Stats should have better performance

### LINKED ISSUE #125: Web: Make the statistics box into a component.

### LINKED ISSUE #142: API: Ranking seems to be wrong

### LINKED ISSUE #143: AWS: Use ALB
We are currently using ELB instead of ALB, we should change this to reduce costs.

### PR DESCRIPTION
**Pull request by Khrall**
Changes:
- API now uses Redis (Fixes #105)
- Routers (endpoints) are imported with es6-imports rather than require
- Stats are cached:
  - Ranking is cached in the User-model (Fixes #142)
  - User count is cached using redis
- Created a StatsBox component for Web (Fixes #125)
- Created a health-endpoint for AWS load balancer (Fixes #143)

### CODE REVIEW

File: web/src/views/app/contestants/Contestants.js [hunk 1]
```diff
@@ -69,8 +69,8 @@ Contestants.propTypes = {
     score: PropTypes.number
   }),
   stats: PropTypes.shape({
-    numberOfUsers: PropTypes.number,
-    userRank: PropTypes.number
+    userCount: PropTypes.number,
+    globalRank: PropTypes.number
   })
 };
```
Comment (hafager) [inline web/src/views/app/contestants/Contestants.js]: Use `StatsBox` here

File: api/src/routes/me/stats.js [hunk 2]
```diff
@@ -1,20 +1,57 @@
...
+      }
+
+      return User.count({})
+      .then(count => {
+        redisClient.setex('usercount', 120, count);
+        return count;
+      });
+    });
+
+const getUserRank = (user) => {
```
Comment (hafager) [inline api/src/routes/me/stats.js]: Use redis instead
